-- XXX: https://stackoverflow.com/questions/692363/quick-sql-question-correct-syntax-for-creating-a-table-with-a-primary-key-in-h2
insert into usuario values (NULL,TRUE,'$2a$10$xlkW1XH8B5PxNC0l5vhMceSPgv.gbgU19RueYF7.dD6S08lvUikcO','das');
insert into rol values (NULL,'shit');
insert into rol values (NULL,'fuck');
insert into rol values (NULL,'crap');
insert into usuario_rol values(1,1);
insert into usuario_rol values(1,3);

--    create table rol (
--        id integer generated by default as identity,
--        nombre varchar(15) not null,
--        primary key (id)
--    )
--    create table usuario (
--        id bigint not null,
--        activo boolean,
--        contra varchar(255),
--        nombre varchar(255),
--        primary key (id)
--    )
--    create table usuario_rol (
--        usuario_id bigint not null,
--        rol_id integer not null,
--        primary key (usuario_id, rol_id)